module.exports = {
  /* ----------------------------- inquiryTransfer ---------------------------- */
  inquiryTransfer: {
    transactionId: "TRX000000062709",
    fromAccountNumber: "1401880008867",
    toAccountNumber: "3970300093970005",
    amount: 100000,
    adminFee: 0,
    transactionFee: 3900,
    totalFee: 3900,
    totalAmount: 103900,
    message: "",
    transactionCategory: "TRANSFER_OA",
    statusCode: "00",
    destCustomerName: "Yohanes Candra",
    fromProductName: "Tab Bisnis Perorangan ",
    toProductName: "Bank BTN",
    accountAlias: "Tab Bisnis Perorangan ",
    additionalData: {},
    challengeCode: null,
    transferOption: "NOW",
  },

  /* ----------------------------- executeTransfer ---------------------------- */
  executeTransfer: {
    additionalData: {
      additionalCost: "string",
      adminFee: 0,
      areaCode: "string",
      biFastProxy: true,
      biFastType: "string",
      citizenship: "string",
      cityCode: "string",
      cityName: "string",
      codeSknRtgs: "string",
      countryCode: "string",
      countryName: "string",
      countrySwiftCode: "string",
      creditorAccountId: "string",
      creditorAccountNumber: "string",
      creditorName: "string",
      creditorNationalId: "string",
      creditorProxyId: "string",
      creditorProxyType: "string",
      creditorResidentStatus: "string",
      creditorTownsName: "string",
      creditorType: "string",
      customerAddress: "string",
      customerName: "string",
      debitorAccountNumber: "string",
      debtorAccountId: "string",
      debtorName: "string",
      debtorNationalId: "string",
      debtorResidentStatus: "string",
      debtorTownsName: "string",
      debtorType: "string",
      donationType: "string",
      email: "string",
      endDate: "string",
      endToEndId: "string",
      expiredDate: 0,
      fileType: "string",
      forex_type: "string",
      frequency: "string",
      frequencyCode: "string",
      fromCurrencyCode: "string",
      fromRateBuy: "string",
      fromRateSell: "string",
      groupName: "string",
      institution: "string",
      invoiceNumber: "string",
      meterNumber: "string",
      nameType: "string",
      noRemitance: "string",
      note: "string",
      ofi: "string",
      originalInvoiceNumber: "string",
      originalTimeLocalTransaction: "string",
      originatingBic: "string",
      paymentInformation: "string",
      payrollType: "string",
      phoneNumber: "string",
      popUpType: "string",
      provision: "string",
      proxyValue: "string",
      qrData: "string",
      receiverType: "string",
      receivingBic: "string",
      recipientBIC: "string",
      recipientCustomerAddress: "string",
      recipientCustomerName: "string",
      regId: "string",
      registrationId: "string",
      registrationStatus: "string",
      relCode: "string",
      reservedPrivate1: "string",
      schemaFee: "string",
      senderPhoneNumber: "string",
      stanTransactionalOriginal: "string",
      startDate: "string",
      terminalId: "string",
      tips: 0,
      toCurrencyCode: "string",
      toRateBuy: "string",
      toRateSell: "string",
      transactionPurpose: "string",
      transactionPurposeDesc: "string",
    },
    adminFee: 2500,
    amount: 13000,
    bankCode: "string",
    fromAccountName: "Tab Bisnis Perorangan ",
    fromAccountNumber: "1401880008867",
    fromDateStr: "string",
    message: "",
    parentTransactionId: "string",
    proxyValue: "string",
    recurringCategory: "string",
    referenceNumber: "string",
    retrievalReferenceNumber: "ESB120806820",
    statusCode: "00",
    statusMessage: "No message",
    toAccountName: "Yohanes Candra",
    toAccountNumber: "3970300093970005",
    toBankName: "string",
    toDateStr: "string",
    totalAmount: 16500,
    totalFee: 3500,
    transactionCategory:
      "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
    transactionChoice: "string",
    transactionDate: "2023-12-04 15:13:5",
    transactionFee: 1000,
    transactionId: "TRX000000062709",
    transactionStatus: "WAITING",
    transactionType: "string",
    transferBIFastType: "string",
    transferOption: "string",
    transferScheduleDto: {
      lastRunDate: "string",
      monthlyRecurring: "string",
      nextRunDate: "string",
      recurringDay: "string",
      recurringDayOfMonth: "string",
      recurringDayOfWeek: "string",
      recurringEnd: "string",
      recurringStart: "string",
      scheduleDate: "string",
      scheduleStatus: 0,
      scheduleType: "string",
    },
    typeFile: "string",
    typePayroll: "string",
  },

  /* ------------------------------- getBankList ------------------------------ */
  getBankList: {
    bankList: [
      {
        areaCode: "4720014",
        bankCode: "472",
        bankName: "Bank Jasa Jakarta",
        bankNetwork: "",
        bankNetworkSecondary: "",
        bankShortName: "BJJ",
        biFastCode: "JAJSIDJ1",
        city: "Jakarta",
        country: "Indonesia",
        createdBy: "",
        createdDate: "2023-12-01T04:48:03.466Z",
        currencyCode: "00",
        deleted: true,
        isInternational: true,
        modifiedBy: "",
        modifiedDate: "2023-12-01T04:48:03.466Z",
        ordering: 0,
        rtgsCode: "JAJSIDJ1",
        sknCode: "JAJSIDJ1",
        swiftCode: "JAJSIDJ1",
        transferBiFastAllowed: true,
        transferOnlineAllowed: true,
        transferRtgsAllowed: true,
        transferSknAllowed: true,
      },
    ],
    newBankList: [
      {
        areaCode: "4720014",
        bankCode: "472",
        bankName: "Bank Jasa Jakarta",
        bankNetwork: "",
        bankNetworkSecondary: "",
        bankShortName: "BJJ",
        biFastCode: "JAJSIDJ1",
        city: "Jakarta",
        country: "Indonesia",
        createdBy: "",
        createdDate: "2023-12-01T04:48:03.466Z",
        currencyCode: "00",
        deleted: true,
        isInternational: true,
        modifiedBy: "",
        modifiedDate: "2023-12-01T04:48:03.466Z",
        ordering: 0,
        rtgsCode: "JAJSIDJ1",
        sknCode: "JAJSIDJ1",
        swiftCode: "JAJSIDJ1",
        transferBiFastAllowed: true,
        transferOnlineAllowed: true,
        transferRtgsAllowed: true,
        transferSknAllowed: true,
      },
    ],
  },
};
