module.exports = {
  /* -------------------------- deletingMassTransfer -------------------------- */
  deletingMassTransfer: {
    isSuccess: true,
  },

  /* ----------------------------- inquiryAccount ----------------------------- */
  inquiryAccount: {
    fileName: "payroll-bank-jasa-jakarta.xlsx",
    itemPayrollDtoList: [
      {
        accountNumber: "12345678900",
        amount: "10000000",
        email: "nasabah_a@gmail.com",
        recipientName: "Nasabah A",
        status: "",
        statusSummaryUploadPayroll: "VALID",
        transactionDescription: "TRANSFER_PAYROLL",
      },
    ],
    message: "",
    parsedExcelRes: {
      fileName: "payroll-bank-jasa-jakarta.xlsx",
      isSuccess: true,
      itemPayrollDtoList: [
        {
          accountNumber: "12345678900",
          amount: "10000000",
          email: "nasabah_a@gmail.com",
          recipientName: "Nasabah A",
          status: "",
          statusSummaryUploadPayroll: "VALID",
          transactionDescription: "TRANSFER_PAYROLL",
        },
      ],
      items: [
        {
          accountNumber: "12345678900",
          amount: 10000000,
          bankCode: "472",
          citizens: "INDONESIAN",
          email: "nasabah_a@gmail.com",
          executionDate: "2023-12-01T04:48:03.466Z",
          recipientName: "Nasabah A",
          recipientType: 0,
          statusSummaryUploadPayroll: "VALID",
          transactionCategory: "TRANSFER_PAYROLL",
          transactionDescription: "TRANSFER_PAYROLL",
        },
      ],
      summaryUploadPayroll: {
        createdDate: "2023-12-01T04:48:03.466Z",
        duplicate: 0,
        notValid: 0,
        numberOfRecordPayroll: 0,
        successUpload: 0,
        totalAmount: 10000000,
        valid: 0,
      },
    },
  },

  /* ----------------------------- saveListPayroll ---------------------------- */
  saveListPayroll: {
    groups: [
      {
        accountNumber: "12345678900",
        createdDate: "2023-12-01T04:48:03.466Z",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678901",
            amount: 10000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_aa@gmail.com",
            executionDate: "",
            recipientName: "Payroll AA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678902",
            amount: 10000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_ab@gmail.com",
            executionDate: "",
            recipientName: "Payroll AB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group A",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 1000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
      {
        accountNumber: "12345678910",
        createdDate: "2023-12-01T04:48:03.466Z",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678911",
            amount: 20000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_ba@gmail.com",
            executionDate: "",
            recipientName: "Payroll BA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678912",
            amount: 20000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_bb@gmail.com",
            executionDate: "",
            recipientName: "Payroll BB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group B",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 2000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
    ],
    isSuccess: true,
  },

  /* --------------------------- getAllMassTransfer --------------------------- */
  getAllMassTransfer: {
    groups: [
      {
        accountNumber: "12345678900",
        createdDate: "",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678901",
            amount: 10000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_aa@gmail.com",
            executionDate: "",
            recipientName: "Payroll AA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678902",
            amount: 10000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_ab@gmail.com",
            executionDate: "",
            recipientName: "Payroll AB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group A",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 1000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
      {
        accountNumber: "12345678910",
        createdDate: "",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678911",
            amount: 20000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_ba@gmail.com",
            executionDate: "",
            recipientName: "Payroll BA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678912",
            amount: 20000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_bb@gmail.com",
            executionDate: "",
            recipientName: "Payroll BB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group B",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 2000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
    ],
  },

  executeMassTransfer: {
    mapList: {
      additionalProp1: [
        {
          accountAlias: "Payroll AA",
          additionalData: {
            additionalCost: "",
            adminFee: 10000,
            areaCode: "4720014",
            biFastProxy: true,
            biFastType: "JAJSIDJ1",
            citizenship: "INDONESIAN",
            cityCode: "",
            cityName: "",
            codeSknRtgs: "JAJSIDJ1",
            countryCode: "",
            countryName: "",
            countrySwiftCode: "JAJSIDJ1",
            creditorAccountId: "",
            creditorAccountNumber: "12345678911",
            creditorName: "Payroll AA",
            creditorNationalId: "",
            creditorProxyId: "",
            creditorProxyType: "",
            creditorResidentStatus: "",
            creditorTownsName: "",
            creditorType: "",
            customerAddress: "",
            customerName: "",
            debitorAccountNumber: "",
            debtorAccountId: "",
            debtorName: "",
            debtorNationalId: "",
            debtorResidentStatus: "",
            debtorTownsName: "",
            debtorType: "",
            donationType: "",
            email: "nasabah_aa@gmail.com",
            endDate: "",
            endToEndId: "",
            expiredDate: 0,
            fileType: "ENCRYPTED",
            forex_type: "",
            frequency: "",
            frequencyCode: "",
            fromCurrencyCode: "",
            fromRateBuy: "",
            fromRateSell: "",
            groupName: "",
            institution: "",
            invoiceNumber: "",
            meterNumber: "",
            nameType: "",
            noRemitance: "",
            note: "",
            ofi: "",
            originalInvoiceNumber: "",
            originalTimeLocalTransaction: "",
            originatingBic: "",
            paymentInformation: "",
            payrollType: "",
            phoneNumber: "",
            popUpType: "",
            provision: "",
            proxyValue: "",
            qrData: "",
            receiverType: "",
            receivingBic: "",
            recipientBIC: "",
            recipientCustomerAddress: "",
            recipientCustomerName: "",
            regId: "",
            registrationId: "",
            registrationStatus: "",
            relCode: "",
            reservedPrivate1: "",
            schemaFee: "",
            senderPhoneNumber: "",
            stanTransactionalOriginal: "",
            startDate: "",
            terminalId: "",
            tips: 0,
            toCurrencyCode: "",
            toRateBuy: "",
            toRateSell: "",
            transactionPurpose: "",
            transactionPurposeDesc: "",
          },
          adminFee: 10000,
          amount: 10000000,
          bankCode: "472",
          fromAccountName: "Payroll BJJ",
          fromAccountNumber: "12345678999",
          maintainBalance: 0,
          maintainPercentage: 0,
          message: "",
          percentage: 0,
          referenceNumber: "TRX000000012345",
          retrievalReferenceNumber: "",
          statusCode: "",
          statusMessage: "",
          toAccountName: "Payroll AA",
          toAccountNumber: "12345678911",
          toBankName: "Bank Jasa Jakarta",
          totalAmount: 10000000,
          totalFee: 10000,
          transactionCategory: "TRANSFER_PAYROLL",
          transactionDate: "",
          transactionFee: 0,
          transactionId: "TRX000000045910",
          transactionStatus: "SUCCESS",
          transactionType: "",
          transferBIFastType: "",
          transferOption: "",
          transferScheduleDto: {
            lastRunDate: "",
            monthlyRecurring: "",
            nextRunDate: "",
            recurringDay: "",
            recurringDayOfMonth: "",
            recurringDayOfWeek: "",
            recurringEnd: "",
            recurringStart: "",
            scheduleDate: "",
            scheduleStatus: 0,
            scheduleType: "",
          },
        },
      ],
      additionalProp2: [
        {
          accountAlias: "Payroll AA",
          additionalData: {
            additionalCost: "",
            adminFee: 10000,
            areaCode: "4720014",
            biFastProxy: true,
            biFastType: "JAJSIDJ1",
            citizenship: "INDONESIAN",
            cityCode: "",
            cityName: "",
            codeSknRtgs: "JAJSIDJ1",
            countryCode: "",
            countryName: "",
            countrySwiftCode: "JAJSIDJ1",
            creditorAccountId: "",
            creditorAccountNumber: "12345678911",
            creditorName: "Payroll AA",
            creditorNationalId: "",
            creditorProxyId: "",
            creditorProxyType: "",
            creditorResidentStatus: "",
            creditorTownsName: "",
            creditorType: "",
            customerAddress: "",
            customerName: "",
            debitorAccountNumber: "",
            debtorAccountId: "",
            debtorName: "",
            debtorNationalId: "",
            debtorResidentStatus: "",
            debtorTownsName: "",
            debtorType: "",
            donationType: "",
            email: "nasabah_aa@gmail.com",
            endDate: "",
            endToEndId: "",
            expiredDate: 0,
            fileType: "ENCRYPTED",
            forex_type: "",
            frequency: "",
            frequencyCode: "",
            fromCurrencyCode: "",
            fromRateBuy: "",
            fromRateSell: "",
            groupName: "",
            institution: "",
            invoiceNumber: "",
            meterNumber: "",
            nameType: "",
            noRemitance: "",
            note: "",
            ofi: "",
            originalInvoiceNumber: "",
            originalTimeLocalTransaction: "",
            originatingBic: "",
            paymentInformation: "",
            payrollType: "",
            phoneNumber: "",
            popUpType: "",
            provision: "",
            proxyValue: "",
            qrData: "",
            receiverType: "",
            receivingBic: "",
            recipientBIC: "",
            recipientCustomerAddress: "",
            recipientCustomerName: "",
            regId: "",
            registrationId: "",
            registrationStatus: "",
            relCode: "",
            reservedPrivate1: "",
            schemaFee: "",
            senderPhoneNumber: "",
            stanTransactionalOriginal: "",
            startDate: "",
            terminalId: "",
            tips: 0,
            toCurrencyCode: "",
            toRateBuy: "",
            toRateSell: "",
            transactionPurpose: "",
            transactionPurposeDesc: "",
          },
          adminFee: 10000,
          amount: 10000000,
          bankCode: "472",
          fromAccountName: "Payroll BJJ",
          fromAccountNumber: "12345678999",
          maintainBalance: 0,
          maintainPercentage: 0,
          message: "",
          percentage: 0,
          referenceNumber: "TRX000000012345",
          retrievalReferenceNumber: "",
          statusCode: "",
          statusMessage: "",
          toAccountName: "Payroll AA",
          toAccountNumber: "12345678911",
          toBankName: "Bank Jasa Jakarta",
          totalAmount: 10000000,
          totalFee: 10000,
          transactionCategory: "TRANSFER_PAYROLL",
          transactionDate: "",
          transactionFee: 0,
          transactionId: "TRX000000045910",
          transactionStatus: "SUCCESS",
          transactionType: "",
          transferBIFastType: "",
          transferOption: "",
          transferScheduleDto: {
            lastRunDate: "",
            monthlyRecurring: "",
            nextRunDate: "",
            recurringDay: "",
            recurringDayOfMonth: "",
            recurringDayOfWeek: "",
            recurringEnd: "",
            recurringStart: "",
            scheduleDate: "",
            scheduleStatus: 0,
            scheduleType: "",
          },
        },
      ],
      additionalProp3: [
        {
          accountAlias: "Payroll AA",
          additionalData: {
            additionalCost: "",
            adminFee: 10000,
            areaCode: "4720014",
            biFastProxy: true,
            biFastType: "JAJSIDJ1",
            citizenship: "INDONESIAN",
            cityCode: "",
            cityName: "",
            codeSknRtgs: "JAJSIDJ1",
            countryCode: "",
            countryName: "",
            countrySwiftCode: "JAJSIDJ1",
            creditorAccountId: "",
            creditorAccountNumber: "12345678911",
            creditorName: "Payroll AA",
            creditorNationalId: "",
            creditorProxyId: "",
            creditorProxyType: "",
            creditorResidentStatus: "",
            creditorTownsName: "",
            creditorType: "",
            customerAddress: "",
            customerName: "",
            debitorAccountNumber: "",
            debtorAccountId: "",
            debtorName: "",
            debtorNationalId: "",
            debtorResidentStatus: "",
            debtorTownsName: "",
            debtorType: "",
            donationType: "",
            email: "nasabah_aa@gmail.com",
            endDate: "",
            endToEndId: "",
            expiredDate: 0,
            fileType: "ENCRYPTED",
            forex_type: "",
            frequency: "",
            frequencyCode: "",
            fromCurrencyCode: "",
            fromRateBuy: "",
            fromRateSell: "",
            groupName: "",
            institution: "",
            invoiceNumber: "",
            meterNumber: "",
            nameType: "",
            noRemitance: "",
            note: "",
            ofi: "",
            originalInvoiceNumber: "",
            originalTimeLocalTransaction: "",
            originatingBic: "",
            paymentInformation: "",
            payrollType: "",
            phoneNumber: "",
            popUpType: "",
            provision: "",
            proxyValue: "",
            qrData: "",
            receiverType: "",
            receivingBic: "",
            recipientBIC: "",
            recipientCustomerAddress: "",
            recipientCustomerName: "",
            regId: "",
            registrationId: "",
            registrationStatus: "",
            relCode: "",
            reservedPrivate1: "",
            schemaFee: "",
            senderPhoneNumber: "",
            stanTransactionalOriginal: "",
            startDate: "",
            terminalId: "",
            tips: 0,
            toCurrencyCode: "",
            toRateBuy: "",
            toRateSell: "",
            transactionPurpose: "",
            transactionPurposeDesc: "",
          },
          adminFee: 10000,
          amount: 10000000,
          bankCode: "472",
          fromAccountName: "Payroll BJJ",
          fromAccountNumber: "12345678999",
          maintainBalance: 0,
          maintainPercentage: 0,
          message: "",
          percentage: 0,
          referenceNumber: "TRX000000012345",
          retrievalReferenceNumber: "",
          statusCode: "",
          statusMessage: "",
          toAccountName: "Payroll AA",
          toAccountNumber: "12345678911",
          toBankName: "Bank Jasa Jakarta",
          totalAmount: 10000000,
          totalFee: 10000,
          transactionCategory: "TRANSFER_PAYROLL",
          transactionDate: "",
          transactionFee: 0,
          transactionId: "TRX000000045910",
          transactionStatus: "SUCCESS",
          transactionType: "",
          transferBIFastType: "",
          transferOption: "",
          transferScheduleDto: {
            lastRunDate: "",
            monthlyRecurring: "",
            nextRunDate: "",
            recurringDay: "",
            recurringDayOfMonth: "",
            recurringDayOfWeek: "",
            recurringEnd: "",
            recurringStart: "",
            scheduleDate: "",
            scheduleStatus: 0,
            scheduleType: "",
          },
        },
      ],
    },
    parentIds: "TRX000000045910",
    sizeTransactions: 0,
    totalAdminFee: 0,
    totalAmount: 10000000,
    totalFee: 10000,
    totalMaintainBalance: 0,
    totalMaintainPercentage: 0,
    totalPercentage: 0,
    totalTransaction: 100010000,
    totalTransactionFee: 10000,
    typeFile: "ENCRYPTED",
    typePayroll: "SUMMARY",
  },
};
