module.exports = {
  /* -------------------------- deletingMassTransfer -------------------------- */
  deletingMassTransfer: {
    isSuccess: true,
  },

  /* ----------------------------- inquiryAccount ----------------------------- */
  inquiryAccount: {
    fileName: "payroll-bank-jasa-jakarta.xlsx",
    itemPayrollDtoList: [
      {
        accountNumber: "12345678900",
        amount: "10000000",
        email: "nasabah_a@gmail.com",
        recipientName: "Nasabah A",
        status: "",
        statusSummaryUploadPayroll: "VALID",
        transactionDescription: "TRANSFER_PAYROLL",
      },
    ],
    message: "",
    parsedExcelRes: {
      fileName: "payroll-bank-jasa-jakarta.xlsx",
      isSuccess: true,
      itemPayrollDtoList: [
        {
          accountNumber: "12345678900",
          amount: "10000000",
          email: "nasabah_a@gmail.com",
          recipientName: "Nasabah A",
          status: "",
          statusSummaryUploadPayroll: "VALID",
          transactionDescription: "TRANSFER_PAYROLL",
        },
      ],
      items: [
        {
          accountNumber: "12345678900",
          amount: 10000000,
          bankCode: "472",
          citizens: "INDONESIAN",
          email: "nasabah_a@gmail.com",
          executionDate: "2023-12-01T04:48:03.466Z",
          recipientName: "Nasabah A",
          recipientType: 0,
          statusSummaryUploadPayroll: "VALID",
          transactionCategory: "TRANSFER_PAYROLL",
          transactionDescription: "TRANSFER_PAYROLL",
        },
      ],
      summaryUploadPayroll: {
        createdDate: "2023-12-01T04:48:03.466Z",
        duplicate: 0,
        notValid: 0,
        numberOfRecordPayroll: 0,
        successUpload: 0,
        totalAmount: 10000000,
        valid: 0,
      },
    },
  },

  /* ----------------------------- saveListPayroll ---------------------------- */
  saveListPayroll: {
    groups: [
      {
        accountNumber: "12345678900",
        createdDate: "2023-12-01T04:48:03.466Z",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678901",
            amount: 10000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_aa@gmail.com",
            executionDate: "",
            recipientName: "Payroll AA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678902",
            amount: 10000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_ab@gmail.com",
            executionDate: "",
            recipientName: "Payroll AB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group A",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 1000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
      {
        accountNumber: "12345678910",
        createdDate: "2023-12-01T04:48:03.466Z",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678911",
            amount: 20000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_ba@gmail.com",
            executionDate: "",
            recipientName: "Payroll BA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678912",
            amount: 20000000,
            bankCode: "472",
            citizens: "INDONESIAN",
            email: "nasabah_bb@gmail.com",
            executionDate: "",
            recipientName: "Payroll BB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group B",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 2000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
    ],
    isSuccess: true,
  },

  /* --------------------------- getAllMassTransfer --------------------------- */
  getAllMassTransfer: {
    groups: [
      {
        accountNumber: "12345678900",
        createdDate: "",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678901",
            amount: 10000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_aa@gmail.com",
            executionDate: "",
            recipientName: "Payroll AA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678902",
            amount: 10000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_ab@gmail.com",
            executionDate: "",
            recipientName: "Payroll AB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group A",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 1000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
      {
        accountNumber: "12345678910",
        createdDate: "",
        groupId: 0,
        isEncrypted: true,
        isSummary: true,
        items: [
          {
            accountNumber: "12345678911",
            amount: 20000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_ba@gmail.com",
            executionDate: "",
            recipientName: "Payroll BA",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
          {
            accountNumber: "12345678912",
            amount: 20000000,
            bankCode: "200",
            citizens: "INDONESIAN",
            email: "nasabah_bb@gmail.com",
            executionDate: "",
            recipientName: "Payroll BB",
            recipientType: 0,
            statusSummaryUploadPayroll: "VALID",
            transactionCategory: "TRANSFER_PAYROLL",
            transactionDescription: "TRANSFER PAYROLL",
          },
        ],
        name: "Payroll Group B",
        numberOfRecordPayroll: 3,
        productName: "Tabungan Payroll",
        totalAmountPayroll: 2000000000,
        transactionDescription: "TRANSFER PAYROLL",
      },
    ],
  },
};
