module.exports = {
  /* -------------------------- getDashboardWithChart ------------------------- */
  getDashboardWithChart: {
    taskCount: {
      waiting: 0,
      approve: 21,
      reject: 5,
    },
    mutasi: [
      {
        referenceId: "REFF SB1033719982",
        amount: 50000.0,
        sign: "C",
        trandesc: "Pemindahbukuan",
        date: "120817",
        time: "145630",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF CA SA",
        remark: "saat ini",
        remark1: "DR 1401300019974 AYI",
        remark3: "IBB852601638 087705480550",
        ticket: "17081293001270070044",
        balance: "50000.0",
        saldoBefore: "0.0",
      },
      {
        referenceId: "REFF SB1033719983",
        amount: 40000.0,
        sign: "C",
        trandesc: "Pemindahbukuan",
        date: "120817",
        time: "133118",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "berita",
        remark1: "DR 1401880001988 NASABAH MA28933",
        remark3: "IBB793500234 085601405256",
        ticket: "17081293001270050291",
        balance: "90000.0",
        saldoBefore: "50000.0",
      },
      {
        referenceId: null,
        amount: 100000.0,
        sign: "C",
        trandesc: "Pemindahbukuan",
        date: "100817",
        time: "093711",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "Sweeping Account",
        remark1: "DR 1401880001988 NASABAH MA28933",
        remark3: "IBB144000678 085601405256",
        ticket: "17081093001270050112",
        balance: "190000.0",
        saldoBefore: "90000.0",
      },
      {
        referenceId: null,
        amount: 40000.0,
        sign: "C",
        trandesc: "Pemindahbukuan",
        date: "100817",
        time: "090452",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "berita",
        remark1: "DR 1401880001988 NASABAH MA28933",
        remark3: "IBB247400284 085601405256",
        ticket: "17081093001270050106",
        balance: "230000.0",
        saldoBefore: "190000.0",
      },
      {
        referenceId: null,
        amount: 207000.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "260717",
        time: "110017",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "",
        remark1: "TRF 1601880000029 QA TEST dua",
        remark3: "IBB178400023 082352491993",
        ticket: "17072693001270047695",
        balance: "23000.0",
        saldoBefore: "230000.0",
      },
      {
        referenceId: null,
        amount: 207000.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "260717",
        time: "110015",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "",
        remark1: "TRF 1601880000087 AGI FAZRILAH ISKANDA",
        remark3: "IBB069200018 082352491993",
        ticket: "17072693001270047693",
        balance: "-184000.0",
        saldoBefore: "23000.0",
      },
      {
        referenceId: null,
        amount: 207000.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "260717",
        time: "110014",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "",
        remark1: "TRF 4701880000022 Sisca Threecya A",
        remark3: "IBB961500013 082352491993",
        ticket: "17072693001270047691",
        balance: "-391000.0",
        saldoBefore: "-184000.0",
      },
      {
        referenceId: null,
        amount: 285718.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "250717",
        time: "111914",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "beritaa acaraa",
        remark1: "TRF 101880000018 NASABAH B318881",
        remark3: "IBB152602873 085269438598",
        ticket: "17072593001270047592",
        balance: "-676718.0",
        saldoBefore: "-391000.0",
      },
      {
        referenceId: null,
        amount: 735278.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "250717",
        time: "111913",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "beritaa acaraa",
        remark1: "TRF 101880000026 NASABAH E584168",
        remark3: "IBB039802868 085269438598",
        ticket: "17072593001270047591",
        balance: "-1411996.0",
        saldoBefore: "-676718.0",
      },
      {
        referenceId: null,
        amount: 285718.0,
        sign: "D",
        trandesc: "Pemindahbukuan",
        date: "240717",
        time: "153042",
        name: "NASABAH MA28933",
        accountNumber: "1401880001352",
        currency: "IDR",
        auxcode: null,
        auxdesc: "TRF SA SA",
        remark: "beritaa acaraa",
        remark1: "TRF 101880000018 NASABAH B318881",
        remark3: "IBB839602781 085269438598",
        ticket: "17072493001270047532",
        balance: "-1697714.0",
        saldoBefore: "-1411996.0",
      },
    ],
    totalCredit: 66642600.0,
    totalDebit: 62796724.0,
    balance: "3795876.00",
    accountNumber: "1401880001352",
  },

  /* ------------------------- getAllCorporateAccount ------------------------- */
  getAllCorporateAccount: {
    accountOwnerName: "Nasabah AA",
    casaAccountList: [
      {
        accountAlias: "Akun 1",
        accountNumber: "123412341234",
        accountNumberMasked: "********1234",
        accountStatus: "1",
        balanceAvailable: 1000000,
        balanceHold: 2000000,
        balanceTotal: 3000000,
        currencyCode: "IDR",
        dateOpen: "2023-11-30T08:07:40.312Z",
        ordering: 0,
        ownerName: "Nasabah AA",
        productName: "Tabungan Bank Jasa",
        productType: "CA",
        sof: true,
        sofAllowed: true,
        statusNumber: 0,
        visible: true,
      },
    ],
    creditCardAccountList: [
      {
        accountNumber: "21901500040666",
        accountStatus: "1",
        accountType: "CCA",
        currencyCode: "IDR",
      },
    ],
    depositAccountList: [
      {
        accountAlias: "Akun 1",
        accountNumber: "123412341236",
        accountNumberMasked: "********1236",
        accountStatus: "1",
        accountType: "DA",
        autoRenewal: true,
        currencyCode: "IDR",
        interestDisbursementAccount: "",
        issueDate: "",
        ledgerBalance: 0,
        maturityDate: "",
        ordering: 0,
        originalBalance: 0,
        ownerName: "NASABAH BB",
        principalDisbursementAccount: "",
        productName: "Tabungan Bank Jasa",
        rate: 0,
        sof: true,
        sofAllowed: true,
        statusNumber: 0,
        term: "",
        termCode: "",
        typeDescription: "",
        typedeposito: "",
        visible: true,
      },
    ],
    giroAccountList: [
      {
        accountAlias: "Akun 1",
        accountNumber: "123412341238",
        accountNumberMasked: "********1238",
        accountStatus: "1",
        accountType: "GA",
        balanceAvailable: 0,
        balanceHold: 0,
        balanceTotal: 0,
        currency: "IDR",
        dateOpen: "2023-11-30T08:07:40.312Z",
        ordering: 0,
        ownerName: "NASABAH CCC",
        productName: "Tabungan Bank Jasa",
        productType: "TR",
        rate: 0,
        sof: true,
        sofAllowed: true,
        statusNumber: 0,
        visible: true,
      },
    ],
    loanAccountList: [
      {
        accountAlias: "Akun 1",
        accountNumber: "123412341244",
        accountNumberMasked: "********1244",
        accountStatus: "1",
        accountType: "LA",
        amountRelease: 0,
        billInterest: 0,
        branchName: "",
        ceiling: 0,
        currencyCode: "IDR",
        drawingLimit: 0,
        fine: 0,
        installmentPeriod: 0,
        loanDescription: "",
        loanType: "",
        maturityDate: "",
        ordering: 0,
        originalAmount: 0,
        originalDate: "",
        ownerName: "",
        penalty: 0,
        principalBill: 0,
        productName: "Tabungan",
        rate: 0,
        remaining: 0,
        sof: true,
        sofAllowed: true,
        statusNumber: 0,
        term: "",
        totalBill: 0,
        usage: 0,
        visible: true,
      },
    ],
    mainAccountBalance: "",
    mainAccountNumber: "",
    mixedAccountList: [
      {
        accountNumber: "123412341294",
        accountNumberMasked: "********1294",
        accountType: "SA",
        currency: "IDR",
        isVisible: true,
      },
    ],
    savingAccountList: [
      {
        accountAlias: "Akun 3",
        accountNumber: "123412341134",
        accountNumberMasked: "********1134",
        accountStatus: "1",
        accountType: "SA",
        balanceAvailable: 4000000,
        balanceHold: 9000000,
        balanceTotal: 13000000,
        currency: "IDR",
        dateOpen: "2023-11-30T08:07:40.313Z",
        ordering: 0,
        ownerName: "NASABAH DD",
        productName: "SA",
        productType: "SA",
        rate: 0,
        sof: true,
        sofAllowed: true,
        statusNumber: 0,
        visible: true,
      },
    ],
  },

  /* ----------------------------- beneficiaryGet ----------------------------- */
  beneficiaryGet: {
    beneficiaryAccounts: [
      {
        accountAddress: "",
        accountNumber: "3970300093970005",
        accountOwnerName: "Yohanes Candra",
        bankAllowed: [""],
        bankCode: "",
        bankName: "",
        bankNameShort: "",
        isDuplicated: true,
        isRegistered: true,
        isValid: true,
        isWaitingToApprove: true,
        proxyValue: "",
        toBankName: "",
        transactionCategory:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
        transactionType:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
      },
      {
        accountAddress: "",
        accountNumber: "3900000094970010",
        accountOwnerName: "Candra",
        bankAllowed: [""],
        bankCode: "",
        bankName: "",
        bankNameShort: "",
        isDuplicated: true,
        isRegistered: true,
        isValid: true,
        isWaitingToApprove: true,
        proxyValue: "",
        toBankName: "",
        transactionCategory:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
        transactionType:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
      },
      {
        accountAddress: "",
        accountNumber: "9970000093970006",
        accountOwnerName: "Alfian Tinangon",
        bankAllowed: [""],
        bankCode: "",
        bankName: "",
        bankNameShort: "",
        isDuplicated: true,
        isRegistered: true,
        isValid: true,
        isWaitingToApprove: true,
        proxyValue: "",
        toBankName: "",
        transactionCategory:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
        transactionType:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
      },
      {
        accountAddress: "",
        accountNumber: "00120998",
        accountOwnerName: "Tinangon",
        bankAllowed: [""],
        bankCode: "",
        bankName: "",
        bankNameShort: "",
        isDuplicated: true,
        isRegistered: true,
        isValid: true,
        isWaitingToApprove: true,
        proxyValue: "",
        toBankName: "",
        transactionCategory:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
        transactionType:
          "TransactionCategory.BANCASSURANCE(channelType=vc, labelIn=BANCASSURANCE, labelEng=BANCASSURANCE)",
      },
    ],
  },

  /* ----------------------------- getCorporateSof ---------------------------- */
  getCorporateSof: {
    sof: [
      {
        accountNumber: "1401880008867",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tab Bisnis Perorangan ",
        productType: "SS",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****8867","currency":"IDR","balanceTotal":14652581.00,"balanceAvailable":13652581.00,"balanceHold":1000000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.5}',
        accountAlias: "Tab Bisnis Perorangan ",
        balance: 13652581.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 4,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401300020103",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Per Pdd - IDR",
        productType: "J1",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0103","currency":"IDR","balanceTotal":1164682.00,"balanceAvailable":1164682.00,"balanceHold":0.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Giro Per Pdd - IDR",
        balance: 1164682.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 5,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401300020111",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Lbg Pdd - IDR",
        productType: "J2",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0111","currency":"IDR","balanceTotal":64220.00,"balanceAvailable":0.00,"balanceHold":1000000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "KPR BP2BT SSN GPM9.5",
        balance: 0.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 6,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901300000044",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Per Pdd - IDR",
        productType: "J1",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0044","currency":"IDR","balanceTotal":327044210.41,"balanceAvailable":327044210.41,"balanceHold":0.00,"dateOpen":1195664400000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.5}',
        accountAlias: "Test Nama Alias RU",
        balance: 327044210.41,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 7,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401500632784",
        accountStatus: 1,
        accountType: "SA",
        productName: "Pratama Prima",
        productType: "SZ",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****2784","currency":"IDR","balanceTotal":1395960.00,"balanceAvailable":1345960.00,"balanceHold":50000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Pratama Prima",
        balance: 1345960.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 8,
        userProfileId: 3536,
      },
      {
        accountNumber: "1402600000728",
        accountStatus: 1,
        accountType: "SA",
        productName: null,
        productType: "T5",
        productCode: null,
        currency: "USD",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0728","currency":"USD","balanceTotal":0.00,"balanceAvailable":0.00,"balanceHold":10.00,"dateOpen":1499101200000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "",
        balance: 0.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 9,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500000789",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa",
        productType: "TB",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0789","currency":"IDR","balanceTotal":137619406.54,"balanceAvailable":137569406.54,"balanceHold":50000.00,"dateOpen":1185296400000,"productName":null,"ownerName":"NASABAH AA07278","rate":2.5}',
        accountAlias: "test nama alias sit",
        balance: 137569406.54,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 12,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500040666",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa",
        productType: "TB",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0666","currency":"IDR","balanceTotal":66500.00,"balanceAvailable":16500.00,"balanceHold":50000.00,"dateOpen":1501088400000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "Tabungan Bank Jasa",
        balance: 16500.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 13,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500040640",
        accountStatus: 1,
        accountType: "SA",
        productName: "Pratama Prima",
        productType: "SZ",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0640","currency":"IDR","balanceTotal":465637.00,"balanceAvailable":415637.00,"balanceHold":50000.00,"dateOpen":1499706000000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Pratama Prima",
        balance: 415637.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 14,
        userProfileId: 3536,
      },
    ],
    dof: [
      {
        accountNumber: "21901580000026",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa - Payroll",
        productType: "TR",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"****0026","currency":"IDR","balanceTotal":14166656.00,"balanceAvailable":14116656.00,"balanceHold":50000.00,"dateOpen":1497805200000,"productName":null,"ownerName":"NASABAH AA07278","rate":2.0}',
        accountAlias: "Tabungan Bank Jasa - Payroll",
        balance: 14116656.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 0,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901880000027",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tab Bisnis Perorangan ",
        productType: "SS",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"****0027","currency":"IDR","balanceTotal":5472221.00,"balanceAvailable":4472221.00,"balanceHold":1000000.00,"dateOpen":1497805200000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.5}',
        accountAlias: "Tab Bisnis Perorangan ",
        balance: 4472221.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 1,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500040624",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa",
        productType: "TB",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"****0624","currency":"IDR","balanceTotal":4185253.00,"balanceAvailable":4135253.00,"balanceHold":50000.00,"dateOpen":1497805200000,"productName":null,"ownerName":"NASABAH AA07278","rate":2.0}',
        accountAlias: "Tabungan Bank Jasa",
        balance: 4135253.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 2,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901580000034",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa - Payroll",
        productType: "TR",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"****0034","currency":"IDR","balanceTotal":1226924.00,"balanceAvailable":1176924.00,"balanceHold":50000.00,"dateOpen":1497891600000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.0}',
        accountAlias: "Tabungan Bank Jasa - Payroll",
        balance: 1176924.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 3,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401880008867",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tab Bisnis Perorangan ",
        productType: "SS",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****8867","currency":"IDR","balanceTotal":14652581.00,"balanceAvailable":13652581.00,"balanceHold":1000000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.5}',
        accountAlias: "Tab Bisnis Perorangan ",
        balance: 13652581.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 4,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401300020103",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Per Pdd - IDR",
        productType: "J1",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0103","currency":"IDR","balanceTotal":1164682.00,"balanceAvailable":1164682.00,"balanceHold":0.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Giro Per Pdd - IDR",
        balance: 1164682.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 5,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401300020111",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Lbg Pdd - IDR",
        productType: "J2",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0111","currency":"IDR","balanceTotal":64220.00,"balanceAvailable":0.00,"balanceHold":1000000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "KPR BP2BT SSN GPM9.5",
        balance: 0.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 6,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901300000044",
        accountStatus: 1,
        accountType: "CA",
        productName: "Giro Per Pdd - IDR",
        productType: "J1",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0044","currency":"IDR","balanceTotal":327044210.41,"balanceAvailable":327044210.41,"balanceHold":0.00,"dateOpen":1195664400000,"productName":null,"ownerName":"NASABAH AA07278","rate":1.5}',
        accountAlias: "Test Nama Alias RU",
        balance: 327044210.41,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 7,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401500632784",
        accountStatus: 1,
        accountType: "SA",
        productName: "Pratama Prima",
        productType: "SZ",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****2784","currency":"IDR","balanceTotal":1395960.00,"balanceAvailable":1345960.00,"balanceHold":50000.00,"dateOpen":1498323600000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Pratama Prima",
        balance: 1345960.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 8,
        userProfileId: 3536,
      },
      {
        accountNumber: "1402600000728",
        accountStatus: 1,
        accountType: "SA",
        productName: null,
        productType: "T5",
        productCode: null,
        currency: "USD",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"*****0728","currency":"USD","balanceTotal":0.00,"balanceAvailable":0.00,"balanceHold":10.00,"dateOpen":1499101200000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "",
        balance: 0.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 9,
        userProfileId: 3536,
      },
      {
        accountNumber: "1401590000387",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa RDN",
        productType: "TV",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"*****0387","currency":"IDR","balanceTotal":0.00,"balanceAvailable":0.00,"balanceHold":0.00,"dateOpen":1499101200000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "Tabungan Bank Jasa RDN",
        balance: 0.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 10,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901580000018",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa - Payroll",
        productType: "TR",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: false,
        additionalData:
          '{"accountNumberMasked":"****0018","currency":"IDR","balanceTotal":94012.00,"balanceAvailable":44012.00,"balanceHold":50000.00,"dateOpen":1497632400000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "Tabungan Bank Jasa - Payroll",
        balance: 44012.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 11,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500000789",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa",
        productType: "TB",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0789","currency":"IDR","balanceTotal":137619406.54,"balanceAvailable":137569406.54,"balanceHold":50000.00,"dateOpen":1185296400000,"productName":null,"ownerName":"NASABAH AA07278","rate":2.5}',
        accountAlias: "test nama alias sit",
        balance: 137569406.54,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 12,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500040666",
        accountStatus: 1,
        accountType: "SA",
        productName: "Tabungan Bank Jasa",
        productType: "TB",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0666","currency":"IDR","balanceTotal":66500.00,"balanceAvailable":16500.00,"balanceHold":50000.00,"dateOpen":1501088400000,"productName":null,"ownerName":"NASABAH AA07278","rate":3.0}',
        accountAlias: "Tabungan Bank Jasa",
        balance: 16500.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 13,
        userProfileId: 3536,
      },
      {
        accountNumber: "21901500040640",
        accountStatus: 1,
        accountType: "SA",
        productName: "Pratama Prima",
        productType: "SZ",
        productCode: null,
        currency: "IDR",
        cardNumber: null,
        cardStatus: null,
        ordering: null,
        isVisible: false,
        isSof: true,
        additionalData:
          '{"accountNumberMasked":"****0640","currency":"IDR","balanceTotal":465637.00,"balanceAvailable":415637.00,"balanceHold":50000.00,"dateOpen":1499706000000,"productName":null,"ownerName":"NASABAH AA07278","rate":0.0}',
        accountAlias: "Pratama Prima",
        balance: 415637.0,
        isPrimary: false,
        accountOwnerName: "NASABAH AA07278",
        proxyValue: null,
        accountLinking: null,
        accountIndex: 14,
        userProfileId: 3536,
      },
    ],
  },

  /* ---------------------------- cashflowByMonthIn --------------------------- */
  cashflowByMonthIn: {
    transactionDto: [
      {
        transactionCategory: "Transfer Masuk",
        amount: 23324910.0,
        percentage: 35.0,
      },
      {
        transactionCategory: "Pendapatan Bunga",
        amount: 9996390.0,
        percentage: 15.0,
      },
      {
        transactionCategory: "Setor Tunai",
        amount: 13328520.0,
        percentage: 20.0,
      },
      {
        transactionCategory: "Lainnya",
        amount: 19992780.0,
        percentage: 30.0,
      },
    ],
    totalAmount: 6.66426e7,
  },

  /* --------------------------- cashflowByMonthOut --------------------------- */
  cashflowByMonthOut: {
    transactionDto: [
      {
        transactionCategory: "Transfer Keluar",
        amount: 15699181.0,
        percentage: 25.0,
      },
      {
        transactionCategory: "Pembayaran",
        amount: 6279672.4,
        percentage: 10.0,
      },
      {
        transactionCategory: "Pembelian",
        amount: 9419508.6,
        percentage: 15.0,
      },
      {
        transactionCategory: "Administrasi Bank",
        amount: 12559344.8,
        percentage: 20.0,
      },
      {
        transactionCategory: "Pembayaran Kredit",
        amount: 9419508.6,
        percentage: 15.0,
      },
      {
        transactionCategory: "Tarik Tunai",
        amount: 6279672.4,
        percentage: 10.0,
      },
      {
        transactionCategory: "Lainnya",
        amount: 3139836.2,
        percentage: 5.0,
      },
    ],
    totalAmount: 62796724,
  },
};
