module.exports = {
  /* ---------------------------- generateSoftToken --------------------------- */
  generateSoftToken: {
    accelerationPriority: 0,
    alphaPremultiplied: true,
    alphaRaster: {
      bounds: {
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
        centerX: 0,
        centerY: 0,
        empty: true,
        height: 0,
        location: {
          x: 0,
          y: 0,
        },
        maxX: 0,
        maxY: 0,
        minX: 0,
        minY: 0,
        size: {
          height: 0,
          width: 0,
        },
        width: 0,
        x: 0,
        y: 0,
      },
      dataBuffer: {
        dataType: 0,
        numBanks: 0,
        offset: 0,
        offsets: [0],
        size: 0,
      },
      height: 0,
      minX: 0,
      minY: 0,
      numBands: 0,
      numDataElements: 0,
      parent: {
        bounds: {
          bounds2D: {
            centerX: 0,
            centerY: 0,
            empty: true,
            height: 0,
            maxX: 0,
            maxY: 0,
            minX: 0,
            minY: 0,
            width: 0,
            x: 0,
            y: 0,
          },
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          location: {
            x: 0,
            y: 0,
          },
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          size: {
            height: 0,
            width: 0,
          },
          width: 0,
          x: 0,
          y: 0,
        },
        dataBuffer: {
          dataType: 0,
          numBanks: 0,
          offset: 0,
          offsets: [0],
          size: 0,
        },
        height: 0,
        minX: 0,
        minY: 0,
        numBands: 0,
        numDataElements: 0,
        sampleModel: {
          dataType: 0,
          height: 0,
          numBands: 0,
          numDataElements: 0,
          sampleSize: [0],
          transferType: 0,
          width: 0,
        },
        sampleModelTranslateX: 0,
        sampleModelTranslateY: 0,
        transferType: 0,
        width: 0,
      },
      sampleModel: {
        dataType: 0,
        height: 0,
        numBands: 0,
        numDataElements: 0,
        sampleSize: [0],
        transferType: 0,
        width: 0,
      },
      sampleModelTranslateX: 0,
      sampleModelTranslateY: 0,
      transferType: 0,
      width: 0,
    },
    colorModel: {
      alphaPremultiplied: true,
      colorSpace: {
        cs_sRGB: true,
        numComponents: 0,
        type: 0,
      },
      componentSize: [0],
      numColorComponents: 0,
      numComponents: 0,
      pixelSize: 0,
      transferType: 0,
      transparency: 0,
    },
    data: {
      bounds: {
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
        centerX: 0,
        centerY: 0,
        empty: true,
        height: 0,
        location: {
          x: 0,
          y: 0,
        },
        maxX: 0,
        maxY: 0,
        minX: 0,
        minY: 0,
        size: {
          height: 0,
          width: 0,
        },
        width: 0,
        x: 0,
        y: 0,
      },
      dataBuffer: {
        dataType: 0,
        numBanks: 0,
        offset: 0,
        offsets: [0],
        size: 0,
      },
      height: 0,
      minX: 0,
      minY: 0,
      numBands: 0,
      numDataElements: 0,
      sampleModel: {
        dataType: 0,
        height: 0,
        numBands: 0,
        numDataElements: 0,
        sampleSize: [0],
        transferType: 0,
        width: 0,
      },
      sampleModelTranslateX: 0,
      sampleModelTranslateY: 0,
      transferType: 0,
      width: 0,
    },
    graphics: {
      clip: {
        bounds: {
          bounds2D: {
            centerX: 0,
            centerY: 0,
            empty: true,
            height: 0,
            maxX: 0,
            maxY: 0,
            minX: 0,
            minY: 0,
            width: 0,
            x: 0,
            y: 0,
          },
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          location: {
            x: 0,
            y: 0,
          },
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          size: {
            height: 0,
            width: 0,
          },
          width: 0,
          x: 0,
          y: 0,
        },
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
      },
      clipBounds: {
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
        centerX: 0,
        centerY: 0,
        empty: true,
        height: 0,
        location: {
          x: 0,
          y: 0,
        },
        maxX: 0,
        maxY: 0,
        minX: 0,
        minY: 0,
        size: {
          height: 0,
          width: 0,
        },
        width: 0,
        x: 0,
        y: 0,
      },
      clipRect: {
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
        centerX: 0,
        centerY: 0,
        empty: true,
        height: 0,
        location: {
          x: 0,
          y: 0,
        },
        maxX: 0,
        maxY: 0,
        minX: 0,
        minY: 0,
        size: {
          height: 0,
          width: 0,
        },
        width: 0,
        x: 0,
        y: 0,
      },
      color: {
        alpha: 0,
        blue: 0,
        colorSpace: {
          cs_sRGB: true,
          numComponents: 0,
          type: 0,
        },
        green: 0,
        red: 0,
        rgb: 0,
        transparency: 0,
      },
      font: {
        attributes: {
          additionalProp1: {},
          additionalProp2: {},
          additionalProp3: {},
        },
        availableAttributes: [{}],
        bold: true,
        family: "string",
        fontName: "string",
        italic: true,
        italicAngle: 0,
        missingGlyphCode: 0,
        name: "string",
        numGlyphs: 0,
        plain: true,
        psname: "string",
        size: 0,
        size2D: 0,
        style: 0,
        transform: {
          determinant: 0,
          identity: true,
          scaleX: 0,
          scaleY: 0,
          shearX: 0,
          shearY: 0,
          translateX: 0,
          translateY: 0,
          type: 0,
        },
        transformed: true,
      },
      fontMetrics: {
        ascent: 0,
        descent: 0,
        font: {
          attributes: {
            additionalProp1: {},
            additionalProp2: {},
            additionalProp3: {},
          },
          availableAttributes: [{}],
          bold: true,
          family: "string",
          fontName: "string",
          italic: true,
          italicAngle: 0,
          missingGlyphCode: 0,
          name: "string",
          numGlyphs: 0,
          plain: true,
          psname: "string",
          size: 0,
          size2D: 0,
          style: 0,
          transform: {
            determinant: 0,
            identity: true,
            scaleX: 0,
            scaleY: 0,
            shearX: 0,
            shearY: 0,
            translateX: 0,
            translateY: 0,
            type: 0,
          },
          transformed: true,
        },
        fontRenderContext: {
          antiAliased: true,
          antiAliasingHint: {},
          fractionalMetricsHint: {},
          transform: {
            determinant: 0,
            identity: true,
            scaleX: 0,
            scaleY: 0,
            shearX: 0,
            shearY: 0,
            translateX: 0,
            translateY: 0,
            type: 0,
          },
          transformType: 0,
          transformed: true,
        },
        height: 0,
        leading: 0,
        maxAdvance: 0,
        maxAscent: 0,
        maxDecent: 0,
        maxDescent: 0,
        widths: [0],
      },
    },
    height: 0,
    minTileX: 0,
    minTileY: 0,
    minX: 0,
    minY: 0,
    numXTiles: 0,
    numYTiles: 0,
    propertyNames: ["string"],
    raster: {
      bounds: {
        bounds2D: {
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          width: 0,
          x: 0,
          y: 0,
        },
        centerX: 0,
        centerY: 0,
        empty: true,
        height: 0,
        location: {
          x: 0,
          y: 0,
        },
        maxX: 0,
        maxY: 0,
        minX: 0,
        minY: 0,
        size: {
          height: 0,
          width: 0,
        },
        width: 0,
        x: 0,
        y: 0,
      },
      dataBuffer: {
        dataType: 0,
        numBanks: 0,
        offset: 0,
        offsets: [0],
        size: 0,
      },
      height: 0,
      minX: 0,
      minY: 0,
      numBands: 0,
      numDataElements: 0,
      parent: {
        bounds: {
          bounds2D: {
            centerX: 0,
            centerY: 0,
            empty: true,
            height: 0,
            maxX: 0,
            maxY: 0,
            minX: 0,
            minY: 0,
            width: 0,
            x: 0,
            y: 0,
          },
          centerX: 0,
          centerY: 0,
          empty: true,
          height: 0,
          location: {
            x: 0,
            y: 0,
          },
          maxX: 0,
          maxY: 0,
          minX: 0,
          minY: 0,
          size: {
            height: 0,
            width: 0,
          },
          width: 0,
          x: 0,
          y: 0,
        },
        dataBuffer: {
          dataType: 0,
          numBanks: 0,
          offset: 0,
          offsets: [0],
          size: 0,
        },
        height: 0,
        minX: 0,
        minY: 0,
        numBands: 0,
        numDataElements: 0,
        sampleModel: {
          dataType: 0,
          height: 0,
          numBands: 0,
          numDataElements: 0,
          sampleSize: [0],
          transferType: 0,
          width: 0,
        },
        sampleModelTranslateX: 0,
        sampleModelTranslateY: 0,
        transferType: 0,
        width: 0,
      },
      sampleModel: {
        dataType: 0,
        height: 0,
        numBands: 0,
        numDataElements: 0,
        sampleSize: [0],
        transferType: 0,
        width: 0,
      },
      sampleModelTranslateX: 0,
      sampleModelTranslateY: 0,
      transferType: 0,
      width: 0,
    },
    sampleModel: {
      dataType: 0,
      height: 0,
      numBands: 0,
      numDataElements: 0,
      sampleSize: [0],
      transferType: 0,
      width: 0,
    },
    source: {},
    sources: [
      {
        colorModel: {
          alphaPremultiplied: true,
          colorSpace: {
            cs_sRGB: true,
            numComponents: 0,
            type: 0,
          },
          componentSize: [0],
          numColorComponents: 0,
          numComponents: 0,
          pixelSize: 0,
          transferType: 0,
          transparency: 0,
        },
        data: {
          bounds: {
            bounds2D: {
              centerX: 0,
              centerY: 0,
              empty: true,
              height: 0,
              maxX: 0,
              maxY: 0,
              minX: 0,
              minY: 0,
              width: 0,
              x: 0,
              y: 0,
            },
            centerX: 0,
            centerY: 0,
            empty: true,
            height: 0,
            location: {
              x: 0,
              y: 0,
            },
            maxX: 0,
            maxY: 0,
            minX: 0,
            minY: 0,
            size: {
              height: 0,
              width: 0,
            },
            width: 0,
            x: 0,
            y: 0,
          },
          dataBuffer: {
            dataType: 0,
            numBanks: 0,
            offset: 0,
            offsets: [0],
            size: 0,
          },
          height: 0,
          minX: 0,
          minY: 0,
          numBands: 0,
          numDataElements: 0,
          sampleModel: {
            dataType: 0,
            height: 0,
            numBands: 0,
            numDataElements: 0,
            sampleSize: [0],
            transferType: 0,
            width: 0,
          },
          sampleModelTranslateX: 0,
          sampleModelTranslateY: 0,
          transferType: 0,
          width: 0,
        },
        height: 0,
        minTileX: 0,
        minTileY: 0,
        minX: 0,
        minY: 0,
        numXTiles: 0,
        numYTiles: 0,
        propertyNames: ["string"],
        sampleModel: {
          dataType: 0,
          height: 0,
          numBands: 0,
          numDataElements: 0,
          sampleSize: [0],
          transferType: 0,
          width: 0,
        },
        sources: [null],
        tileGridXOffset: 0,
        tileGridYOffset: 0,
        tileHeight: 0,
        tileWidth: 0,
        width: 0,
      },
    ],
    tileGridXOffset: 0,
    tileGridYOffset: 0,
    tileHeight: 0,
    tileWidth: 0,
    transparency: 0,
    type: 0,
    width: 0,
    writableTileIndices: [
      {
        x: 0,
        y: 0,
      },
    ],
  },
};
