module.exports = {
  /* ----------------------------- CORPORATE LOGIN ----------------------------- */
  corporateLogin: {
    status: 200,
    data: {
      fullName: "Salwa Qurota Ayun",
      nameAlias: "AKIMAK",
      languange: "IDN",
      email: "pebinurhakim200299@gmail.com",
      phoneNumber: "+6285601405256",
      role: 6,
      menuAccess: [
        {
          id: 315,
          name_id: "Proxy BI FAST",
          name_en: "Proxy BI FAST",
          order: 1,
          description: "Child of Layanan Nasabah",
          parent_id: 283,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 316,
          name_id: "Reward Tabungan Bisnis",
          name_en: "Business Saving Rewards",
          order: 2,
          description: "Child of Layanan Nasabah",
          parent_id: 283,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 396,
          name_id: "Layanan Kartu ATM/Debit",
          name_en: "ATM/Debit Card Service",
          order: 3,
          description: "Child of Layanan Nasabah",
          parent_id: 283,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 34,
          name_id: "Gas Negara",
          name_en: "State Gas",
          order: 11,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 35,
          name_id: "Pinjaman",
          name_en: "Loan",
          order: 12,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 29,
          name_id: "Penerimaan Negara",
          name_en: "State Revenue",
          order: 5,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 30,
          name_id: "Pajak Daerah",
          name_en: "Local Tax",
          order: 7,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 31,
          name_id: "Akun Virtual",
          name_en: "Virtual Account",
          order: 8,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 32,
          name_id: "Tiket",
          name_en: "Ticket",
          order: 9,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 37,
          name_id: "Amal",
          name_en: "Charity",
          order: 14,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 25,
          name_id: "Pinjaman BTN",
          name_en: "BTN Loan",
          order: 1,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 38,
          name_id: "Daftar Pembayaran",
          name_en: "Payment List",
          order: 99,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 7,
          name_id: "Pajak Kendaraan",
          name_en: "Vehicle Tax",
          order: 24,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 33,
          name_id: "BPJS",
          name_en: "BPJS",
          order: 10,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 291,
          name_id: "Non Financial",
          name_en: "Non Financial",
          order: 0,
          description: "",
          parent_id: 290,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 292,
          name_id: "Financial",
          name_en: "Financial",
          order: 1,
          description: "",
          parent_id: 290,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 293,
          name_id: "Login Perusahaan",
          name_en: "Corporate Login",
          order: 2,
          description: "",
          parent_id: 290,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 294,
          name_id: "Penggunaan Limit",
          name_en: "Limit Usage",
          order: 3,
          description: "",
          parent_id: 290,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 41,
          name_id: "Listrik Prepaid",
          name_en: "Prepaid Electricity",
          order: 2,
          description: "Child of Purchase",
          parent_id: 39,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 40,
          name_id: "Pulsa & Data",
          name_en: "Pulsa & Data",
          order: 1,
          description: "Child of Purchase",
          parent_id: 39,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 234,
          name_id: "Daftar Pembelian",
          name_en: "Purchase List",
          order: 8,
          description: "Child of Purchase",
          parent_id: 39,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 66,
          name_id: "Sweep-in",
          name_en: "Sweep-in",
          order: 1,
          description: "Child of Account Sweeping",
          parent_id: 65,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 20,
          name_id: "Pindah Dana",
          name_en: "Own Account Transfer",
          order: 1,
          description: "Child of Transfer",
          parent_id: 19,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 23,
          name_id: "Bank Lain",
          name_en: "Domestic Bank Transfer",
          order: 3,
          description: "Child of Transfer",
          parent_id: 19,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 22,
          name_id: "Daftar Penerima Transfer",
          name_en: "Transfer Destination List",
          order: 6,
          description: "Child of Transfer",
          parent_id: 19,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 3,
          name_id: "Dummy 2",
          name_en: "Dummy 2",
          order: 1,
          description: "",
          parent_id: 1,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 5,
          name_id: "All Dummy",
          name_en: "All Dummy",
          order: 3,
          description: "",
          parent_id: 1,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 4,
          name_id: "Dummy 3",
          name_en: "Dummy 3",
          order: 2,
          description: "",
          parent_id: 1,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 209,
          name_id: "Registrasi VA",
          name_en: "VA Registration",
          order: 1,
          description: null,
          parent_id: 208,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 210,
          name_id: "Pembuatan VA",
          name_en: "Create VA",
          order: 2,
          description: null,
          parent_id: 208,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 211,
          name_id: "Pengaturan VA",
          name_en: "VA Setting",
          order: 3,
          description: null,
          parent_id: 208,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 213,
          name_id: "Laporan VA",
          name_en: "VA Report",
          order: 5,
          description: null,
          parent_id: 208,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 212,
          name_id: "Management VA",
          name_en: "VA Management",
          order: 4,
          description: null,
          parent_id: 208,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 311,
          name_id: "Valuta Asing",
          name_en: "Valuta Asing",
          order: 2,
          description: "Child of Payroll",
          parent_id: 48,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 310,
          name_id: "Sesama Mata Uang",
          name_en: "Same Currency",
          order: 1,
          description: "Child of Payroll",
          parent_id: 48,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 236,
          name_id: "Pembukaan Rekening",
          name_en: "Opening Secondary Account",
          order: 0,
          description: "Child of Opening Secondary Account",
          parent_id: 235,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 203,
          name_id: "Pembayaran",
          name_en: "Payment",
          order: 2,
          description: null,
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 207,
          name_id: "Virtual Account",
          name_en: "Virtual Account",
          order: 5,
          description: "",
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 201,
          name_id: "Daftar Penerima Transfer",
          name_en: "Transfer Destination List",
          order: 0,
          description: null,
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 202,
          name_id: "Transfer",
          name_en: "Transfer",
          order: 1,
          description: null,
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 204,
          name_id: "Pembelian ",
          name_en: "Purchase",
          order: 3,
          description: null,
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 205,
          name_id: "Account Sweeping",
          name_en: "Account Sweeping",
          order: 4,
          description: null,
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 391,
          name_id: "Layanan Nasabah",
          name_en: "Customer Service",
          order: 7,
          description: "",
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 390,
          name_id: "Pembayaran Gaji",
          name_en: "Payroll",
          order: 6,
          description: "",
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 392,
          name_id: "Auto Collection",
          name_en: "Auto Collection",
          order: 8,
          description: "",
          parent_id: 206,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 306,
          name_id: "QR CPM",
          name_en: "QR CPM",
          order: 0,
          description: "",
          parent_id: 305,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 307,
          name_id: "QR MPM",
          name_en: "QR MPM",
          order: 1,
          description: "",
          parent_id: 305,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 374,
          name_id: "Cashflow Tracker",
          name_en: "Cashflow Tracker",
          order: 0,
          description: "Parent Auto Collection",
          parent_id: 372,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 375,
          name_id: "Promo",
          name_en: "Promo",
          order: 0,
          description: "Parent Auto Collection",
          parent_id: 373,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 370,
          name_id: "Registrasi Rekening",
          name_en: "Registration Account",
          order: 1,
          description: "Child of Auto Collection",
          parent_id: 369,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 371,
          name_id: "Sesama Mata Uang",
          name_en: "Same Currency",
          order: 2,
          description: "Child of Auto Collection",
          parent_id: 369,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 283,
          name_id: "Layanan Nasabah",
          name_en: "Customer Service",
          order: 0,
          description: "Parent of Layanan Nasabah",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 24,
          name_id: "Pembayaran",
          name_en: "Payment",
          order: 6,
          description: "Parent of Payment",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 290,
          name_id: "Laporan",
          name_en: "Report",
          order: 3,
          description: "",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 39,
          name_id: "Pembelian",
          name_en: "Purchase",
          order: 0,
          description: "Parent of Purchase",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 65,
          name_id: "Account Sweeping",
          name_en: "Account Sweeping",
          order: 0,
          description: "Parent of Account Sweeping",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 19,
          name_id: "Transfer",
          name_en: "Transfer",
          order: 0,
          description: "Parent of Transfer",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 1,
          name_id: "Parent Dummy",
          name_en: "Parent Dummy",
          order: 6,
          description: "",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 208,
          name_id: "Virtual Account",
          name_en: "Virtual Account",
          order: 0,
          description: "parent of virtual account",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 48,
          name_id: "Gaji",
          name_en: "Payroll",
          order: 0,
          description: "Parent of Payroll",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 235,
          name_id: "Pembukaan Rekening",
          name_en: "Opening Secondary Account",
          order: 0,
          description: "Parent of Opening Secondary Account",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 206,
          name_id: "Daftar Tugas",
          name_en: "Pending Task",
          order: null,
          description: "Parent daftar tugas",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 305,
          name_id: "QRIS",
          name_en: "QRIS",
          order: 7,
          description: "",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 372,
          name_id: "Cashflow Tracker",
          name_en: "Cashflow Tracker",
          order: 0,
          description: "Parent Auto Collection",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 373,
          name_id: "Promo",
          name_en: "Promo",
          order: 0,
          description: "Parent Auto Collection",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 369,
          name_id: "Auto Collection",
          name_en: "Auto Collection",
          order: 0,
          description: "Parent Of Auto Collection",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 9,
          name_id: "Rekening",
          name_en: "Account",
          order: 0,
          description: "",
          parent_id: null,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 10,
          name_id: "Tabungan",
          name_en: "Saving",
          order: 1,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 11,
          name_id: "Giro",
          name_en: "Current",
          order: 2,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 12,
          name_id: "Deposito",
          name_en: "Deposit",
          order: 3,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 13,
          name_id: "Pinjaman",
          name_en: "Loan",
          order: 4,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 15,
          name_id: "Rekening Koran",
          name_en: "Bank Statement",
          order: 6,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 16,
          name_id: "Mutasi",
          name_en: "Mutation",
          order: 7,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 17,
          name_id: "Pengaturan Rekening",
          name_en: "Account Settings",
          order: 8,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 14,
          name_id: "Gabungan",
          name_en: "Joint",
          order: 5,
          description: "",
          parent_id: 9,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 36,
          name_id: "Pegadaian",
          name_en: "Pegadaian",
          order: 13,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 56,
          name_id: "Ecommerce",
          name_en: "Ecommerce",
          order: 22,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 50,
          name_id: "PDAM",
          name_en: "PDAM",
          order: 16,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 28,
          name_id: "Kartu Kredit",
          name_en: "Credit Card",
          order: 4,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 26,
          name_id: "Listrik",
          name_en: "Electricity",
          order: 2,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 27,
          name_id: "Telepon",
          name_en: "Telephone",
          order: 3,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 51,
          name_id: "Asuransi",
          name_en: "Insurance",
          order: 17,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 52,
          name_id: "Pendidikan",
          name_en: "Education",
          order: 18,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 53,
          name_id: "Konsolidasi",
          name_en: "Consolidation",
          order: 19,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 57,
          name_id: "Internet & TV",
          name_en: "Internet & TV",
          order: 23,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 54,
          name_id: "IPL",
          name_en: "IPL",
          order: 20,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 55,
          name_id: "Multibiller",
          name_en: "Multibiller",
          order: 21,
          description: "Child of Payment",
          parent_id: 24,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 68,
          name_id: "Sweep-excess fund",
          name_en: "Sweep-excess fund",
          order: 3,
          description: "Child of Account Sweeping",
          parent_id: 65,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 67,
          name_id: "Sweep-out",
          name_en: "Sweep-out",
          order: 2,
          description: "Child of Account Sweeping",
          parent_id: 65,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
        {
          id: 21,
          name_id: "Sesama BTN",
          name_en: "BTN Transfer",
          order: 2,
          description: "Child of Transfer",
          parent_id: 19,
          group: null,
          menuTypeId: null,
          menuTypeName: null,
          searchBy: null,
          menuAccessChild: null,
          masterMenuIdList: null,
          isApprovalMatrixAdmin: null,
          isFinancialMenu: null,
          isAllServiceMenu: null,
          isApprovalMatrixMenu: null,
          isPrivilegeSettingPortal: null,
          corporateProfileId: null,
        },
      ],
      corporateProfile: {
        corporateId: "KEVIN01",
        corporateProfileId: 585,
        cif: "AA07278",
        corporateName: "Salwa Tech",
        corporateField: "1",
        corporateAddress: "YOGYAKARTA, INDONESIA, BAHAGIA",
        corporateContact: "0895322424668",
        accountNumber: "21901300000044",
      },
      corporateConfig: {
        corporateStatus: true,
      },
      isMultiple: false,
    },
    headers: {
      access_token: "d35cece3-9745-4e2b-9c41-59b735238cac",
      "content-type": "application/json;charset=UTF-8",
      expire: "900",
    },
  },

  /* ----------------------------- CORPORATE LOGOUT ---------------------------- */
  corporateLogout: {
    success: true,
  },
};
